# Site Settings
title: welcome to visit Blog for Infinity Study
email: pydevrio@gmail.com
description: blog for infinity study
baseurl: "/infinityStudy.github.io" # the subpath of your site, e.g. /blog
url: "https://infinityStudy.gitgub.io" # the base hostname & protocol for your site
google_analytics: ""

# User Settings
username: infinityStudy
user_description: ....user description
disqus_username: unclepig_good
# Social Media
# Remove the item if you don't need it
github_username: infinityStudy
facebook_username: pydevrio
twitter_username: pydevrio
instagram_username: pydevrio
linkedin_username: pydevrio
medium_username: pydevrio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
